"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
i = 1
i_next = 1
sum_even = 0
while i < 4000000:
	if i % 2 == 0:
		sum_even += i
	i, i_next = i_next, i_next + i
	i += 1
print("The sum of even number under four million in Fibonacci is : ", sum_even)